# General Purpose Learning Paths Dataset

COURSES = [
    {
        "id": 1,
        "name": "Introduction to Computers & Digital Literacy",
        "duration": "30-40 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Basic Computer Skills", "Digital Literacy"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)"],
        "goals": ["Get a Job", "Learn Something New", "Upgrade Skills for Current Job"],
        "description": "Foundation course covering computer basics, internet, email, and essential office tools.",
        "apply_link": "https://www.coursera.org"
    },
    {
        "id": 2,
        "name": "Microsoft Office & Productivity Tools",
        "duration": "20-40 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Basic Computer Skills", "Digital Literacy"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Learn Something New", "Upgrade Skills for Current Job"],
        "description": "Learn Word, Excel, PowerPoint, and other productivity tools used in offices worldwide.",
        "apply_link": "https://www.coursera.org"
    },
    {
        "id": 3,
        "name": "Web Development Fundamentals (HTML, CSS, JavaScript)",
        "duration": "60-120 Hours",
        "fees": "Free / Paid",
        "level": "beginner",
        "qualifications": ["School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Web Development"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Learn Something New", "Start a Business", "Upgrade Skills for Current Job"],
        "description": "Build websites from scratch — covering HTML structure, CSS styling, and JavaScript interactivity.",
        "apply_link": "https://www.freecodecamp.org"
    },
    {
        "id": 4,
        "name": "Full-Stack Web Development",
        "duration": "6-12 Months",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Web Development"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Higher Education", "Upgrade Skills for Current Job", "Start a Business"],
        "description": "Complete front-end and back-end development including React, Node.js, databases, and deployment.",
        "apply_link": "https://www.udemy.com"
    },
    {
        "id": 5,
        "name": "Python Programming (Beginner to Intermediate)",
        "duration": "40-60 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Python Programming"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)"],
        "goals": ["Get a Job", "Learn Something New", "Higher Education", "Upgrade Skills for Current Job"],
        "description": "Learn Python from zero — variables, loops, functions, OOP, and real-world projects.",
        "apply_link": "https://www.python.org/about/gettingstarted/"
    },
    {
        "id": 6,
        "name": "Artificial Intelligence & Machine Learning with Python",
        "duration": "60-120 Hours",
        "fees": "Free / Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Artificial Intelligence and Machine Learning", "Python Programming"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Higher Education"],
        "description": "Covers AI/ML concepts with Python including supervised learning, neural networks, and model deployment.",
        "apply_link": "https://www.coursera.org"
    },
    {
        "id": 7,
        "name": "Data Science & Analytics",
        "duration": "60-120 Hours",
        "fees": "Free / Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Data Science and Analytics", "Python Programming"],
        "skills": ["Basic (Some computer knowledge)", "Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Higher Education"],
        "description": "Statistics, Python/R, data visualization, and machine learning for real-world data analysis.",
        "apply_link": "https://www.kaggle.com/learn"
    },
    {
        "id": 8,
        "name": "SQL & Database Management",
        "duration": "20-40 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Database and SQL", "Data Science and Analytics"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Learn Something New", "Upgrade Skills for Current Job"],
        "description": "Master SQL queries, database design, and MySQL/PostgreSQL for data management.",
        "apply_link": "https://www.w3schools.com/sql/"
    },
    {
        "id": 9,
        "name": "Introduction to Generative AI & Prompt Engineering",
        "duration": "5-10 Hours",
        "fees": "FREE",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Artificial Intelligence and Machine Learning"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Learn Something New", "Get a Job", "Upgrade Skills for Current Job"],
        "description": "Free introductory course on Generative AI, LLMs, and effective prompt engineering techniques.",
        "apply_link": "https://www.coursera.org"
    },
    {
        "id": 10,
        "name": "Cyber Security Fundamentals",
        "duration": "40-80 Hours",
        "fees": "Free / Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Cyber Security"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Learn Something New", "Higher Education"],
        "description": "Network security, ethical hacking basics, cyber laws, and defensive security practices.",
        "apply_link": "https://www.cybrary.it"
    },
    {
        "id": 11,
        "name": "Cloud Computing (AWS / Azure / GCP)",
        "duration": "40-80 Hours",
        "fees": "Free / Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Cloud Computing"],
        "skills": ["Basic (Some computer knowledge)", "Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Higher Education", "Learn Something New"],
        "description": "Cloud architecture, deployment, virtual machines, and managed services on major cloud platforms.",
        "apply_link": "https://aws.amazon.com/training/"
    },
    {
        "id": 12,
        "name": "Embedded Systems & IoT Development",
        "duration": "80-120 Hours",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (CS/IT)", "Graduate (Any Stream)", "Post Graduate"],
        "interests": ["Embedded Systems and IoT"],
        "skills": ["Basic (Some computer knowledge)", "Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Higher Education", "Upgrade Skills for Current Job", "Learn Something New", "Start a Business"],
        "description": "Embedded C, microcontrollers, RTOS, Arduino, Raspberry Pi, and IoT project development.",
        "apply_link": "https://www.udemy.com"
    },
    {
        "id": 13,
        "name": "Introduction to Python (FREE)",
        "duration": "2-5 Hours",
        "fees": "FREE",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Python Programming"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)"],
        "goals": ["Learn Something New", "Get a Job", "Higher Education"],
        "description": "Free bite-sized introduction to Python — variables, loops, and simple programs.",
        "apply_link": "https://www.learnpython.org"
    },
    {
        "id": 14,
        "name": "Digital Marketing & Social Media",
        "duration": "20-40 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Post Graduate"],
        "interests": ["Digital Marketing", "Basic Computer Skills"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Start a Business", "Upgrade Skills for Current Job", "Learn Something New"],
        "description": "SEO, social media marketing, content creation, Google Ads, and analytics for modern businesses.",
        "apply_link": "https://skillshop.withgoogle.com"
    },
    {
        "id": 15,
        "name": "DevOps & CI/CD Fundamentals",
        "duration": "40-80 Hours",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Cloud Computing", "Web Development"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Higher Education"],
        "description": "Docker, Kubernetes, Jenkins, Git workflows, and automated deployment pipelines.",
        "apply_link": "https://www.udemy.com"
    },
    {
        "id": 16,
        "name": "Data Engineering & Big Data",
        "duration": "80-120 Hours",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Data Science and Analytics", "Database and SQL"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Higher Education", "Upgrade Skills for Current Job"],
        "description": "Big data pipelines, Apache Spark, data lakes, ETL processes, and analytics engineering.",
        "apply_link": "https://www.coursera.org"
    },
    {
        "id": 17,
        "name": "Mobile App Development (Android / iOS)",
        "duration": "60-120 Hours",
        "fees": "Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Web Development", "Python Programming"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Start a Business", "Upgrade Skills for Current Job", "Higher Education"],
        "description": "Build native or cross-platform mobile apps using Flutter, React Native, or Kotlin.",
        "apply_link": "https://developer.android.com/courses"
    },
    {
        "id": 18,
        "name": "Graphic Design & UI/UX",
        "duration": "30-60 Hours",
        "fees": "Free / Paid",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Post Graduate"],
        "interests": ["Graphic Design", "Web Development"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Start a Business", "Learn Something New", "Upgrade Skills for Current Job"],
        "description": "Visual design principles, Figma, Adobe tools, and UX research for digital products.",
        "apply_link": "https://www.figma.com/resources/learn-design/"
    },
    {
        "id": 19,
        "name": "Chip Design & VLSI (Advanced)",
        "duration": "80-120 Hours",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["Diploma", "Graduate (CS/IT)", "Graduate (Any Stream)", "Post Graduate"],
        "interests": ["Chip Design and VLSI", "Embedded Systems and IoT"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Higher Education", "Learn Something New", "Upgrade Skills for Current Job"],
        "description": "VLSI design, HDL programming, Verilog/VHDL, and semiconductor chip development.",
        "apply_link": "https://www.udemy.com"
    },
    {
        "id": 20,
        "name": "Freelancing & Remote Work Skills",
        "duration": "10-20 Hours",
        "fees": "Free / Low Cost",
        "level": "beginner",
        "qualifications": ["No formal qualification needed", "School (up to 10th)", "High School (12th)", "Diploma", "Graduate (Any Stream)", "Post Graduate"],
        "interests": ["Digital Marketing", "Basic Computer Skills", "Web Development"],
        "skills": ["Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Start a Business", "Get a Job", "Learn Something New"],
        "description": "How to find clients, build a portfolio, price services, and work remotely as a freelancer.",
        "apply_link": "https://www.upwork.com"
    },
    {
        "id": 21,
        "name": "Advanced Cyber Security & Ethical Hacking",
        "duration": "80-120 Hours",
        "fees": "Paid",
        "level": "advanced",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Cyber Security"],
        "skills": ["Intermediate (Working knowledge)", "Advanced (Professional level)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Higher Education", "Learn Something New"],
        "description": "Advanced penetration testing, SOC operations, digital forensics, and security certifications (CEH, OSCP).",
        "apply_link": "https://www.cybrary.it"
    },
    {
        "id": 22,
        "name": "AWS Cloud Practitioner / Solutions Architect",
        "duration": "30-60 Hours",
        "fees": "Paid",
        "level": "intermediate",
        "qualifications": ["High School (12th)", "Diploma", "Graduate (Any Stream)", "Graduate (CS/IT)", "Post Graduate"],
        "interests": ["Cloud Computing"],
        "skills": ["Complete Beginner (No prior knowledge)", "Basic (Some computer knowledge)", "Intermediate (Working knowledge)"],
        "goals": ["Get a Job", "Upgrade Skills for Current Job", "Learn Something New"],
        "description": "AWS certification preparation covering EC2, S3, Lambda, VPC, and cloud architecture patterns.",
        "apply_link": "https://aws.amazon.com/certification/"
    }
]
